INHERIT: config/nav.yml

site_name: Got 文档
site_url: https://wdk-docs.github.io/got-docs/
site_author: Sindre Sorhus
site_description: Got 文档
docs_dir: content
site_dir: docs
dev_addr: 127.0.0.1:8001
extra_css:
  - stylesheets/extra.css

repo_name: wdk-docs/got-docs
repo_url: https://github.com/wdk-docs/got-docs
edit_uri: edit/master/content

theme:
  name: material
  logo: assets/logo/logo.svg
  favicon: assets/favicons/favicon.ico
  language: zh
  # custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.indexes # 父菜单索引
    # - navigation.sections # 全部展开
    # - navigation.expand # 打开收缩
    - content.code.annotate
    - navigation.top # 返回头部

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 
        - content/examples
        - content/includes
      auto_append:
        - abbreviations.md
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.magiclink

plugins:
  search:
    # Spaces, dashes, periods and forward-slash (so serving.knative.dev/blibble can be searched as blibble).
    separator: '[\/\s\-\.]+'
  # macros:
  #   module_name: hack/macros
  #   include_dir: source/snippets
  exclude:
    glob:
      # Exclude files that contain hugo specific shortcodes
      # (either the include shortcode or not-converted-yet tabs).
      - snippets/*
      - smoketest.md
  awesome-pages:
    filename: ".index"
    collapse_single_pages: true
    strict: false
  blogging:
    # locale: zh-CN
    # {{ blog_content }}
    dirs: # The directories to be included
      - blog
    features:
      tags: {}
    # {{ blog_content review }}
    categories:
      - name: review
        dirs:
          - review
  tags:
    tags_file: tags.md
copyright: "版权所有 © 2017-2023 MIT by Sindre Sorhus"

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sindresorhus
      name: Sindre Sorhus Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/sindresorhus
      name: Sindre Sorhus Github
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/sindresorhus
      name: Sindre Sorhus Instagram
    - icon: fontawesome/brands/blogger
      link: https://sindresorhus.com/apps
      name: Sindre Sorhus Blog 
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@sindresorhus
      name: Sindre Sorhus Mastodon
  version_warning: !!python/object/apply:os.getenv ["VERSION_WARNING"]
  knative_version: !!python/object/apply:os.getenv ["KNATIVE_VERSION"]
  branch: !!python/object/apply:os.getenv ["SAMPLES_BRANCH", "main"]
  # analytics:
  #   provider: google
  #   property: G-YRMNFYE32R
  # version:
  #   provider: mike
