nav:
  - 1-promise.md
  - 10-instances.md
  - Improve docs
  - 2-options.md
  - 3-streams.md
  - 4-pagination.md
  - 5-https.md
  - 6-timeout.md
  - 7-retry.md
  - 8-errors.md
  - 9-hooks.md
  - async-stack-traces.md
  - cache.md
  - lets-make-a-plugin.md
  - quick-start.md
  - tips.md
  - typescript.md
